server:
  port: ${APP.PORT}
  servlet:
    context-path: /task-management

spring:
  datasource:
    url: r2dbc:postgresql://${DB.URL}/${DB.NAME}
    username: ${DB.USER}
    password: ${DB.PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

task:
  repository:
    type: ${DB.TYPE}
